# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e7645a5fc35350b5968d49947a7cfcfdd2fc7dacef9470217dad886ec688a30fe87a3a9ee5f553b78b1551357eee4c4884be815cf0735466382a48e18230294

test:
  secret_key_base: 6906da8f62b097980e681ac127b219ae321b11c96083594bfb24dc65a6c0cafe911c6690feb0b35062f8222636aa055b331ca236e942b14b349455fcb5209a32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
